version: '3'

services:
  php:
    build: ./php
    ports:
      - 5002:80
    volumes:
      - ./php:/php-app
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  jenkins:
    build: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /jenkins_home/:/var/jenkins_home/
