-
  name: play
  hosts: 127.0.0.1
  connection: local
  
#  name: play
#  hosts: localhost
#  tasks:
#    - command: echo HELLO
#  -  name: make mkdir
#     docker_container:
#       name: vagrant_php_1
#       command: mkdir /qqqq
