version: '3.3'
services:
  wordpress:
    build: ./wordpress
    depends_on:
       - db
  #image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

    ports:
       - "8089:80"
    restart: always
