node {
    def app
    def app_sql


    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        git(
        branch: 'master',
        url: 'https://github.globant.com/lucas-ducau/DevOps-Academy.git',
        credentialsId: 'github-globant')
    }

    stage('Build images') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

       app = docker.build("lucasducau/wordpress_qqqq:${env.BUILD_ID}","./wordpress/")
//        app = docker.build './wordpress/'
       app_sql = docker.build("lucasducau/sql_qqqq:${env.BUILD_ID}","./sql")
//        app_sql = docker.build("lucasducau/sql_qqqq:${env.BUILD_ID}","./sql")
    }

    stage('Test wordpress') {
        /* Ideally, we would run a test framework against our image.
         * For this example, we're using a Volkswagen-type approach ;-) */

       app.inside {
             sh 'cd /var/www/html/ && ./wp_test.sh'
        }
    }

    stage('Push images') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app_sql.push("${env.BUILD_NUMBER}")
            app_sql.push("latest")
        }
    }
}
  /*  stage('Clean up')
   {
        sh 'docker system prune -f -a --volumes'
    }*/
}
