node ('docker-agent') {
    def app_golang



    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        git(
        branch: 'master',
        url: 'https://github.globant.com/lucas-ducau/DevOps-Academy.git',
        credentialsId: 'github-globant')
    }

    stage('Build images') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

       app_golang = docker.build("lucasducau/golang_qqqq:${env.BUILD_ID}","./golang/").run("-p 8081:8081")

    }
try{
    stage('Test golang') {
        /* Ideally, we would run a test framework against our image.
         * For this example, we're using a Volkswagen-type approach ;-) */




          sh  'curl http://10.210.8.34:8081/ | grep Hello && echo "Tests passed." || ( echo "Tests failed." && exit 1 )'


         }
} catch (Exception e){
  app_golang.stop()

  echo "Tests failed"
  sh 'exit 1'
}
try{
     stage('Push images') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
         withCredentials([usernamePassword( credentialsId: 'docker-hub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {

         docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
             sh "docker login -u ${USERNAME} -p ${PASSWORD}"
             sh "docker push lucasducau/golang_qqqq:${env.BUILD_ID}"

        /*     app.push("${env.BUILD_ID}")
             app.push("latest")*/
            }
}
      /*  docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            pushapp.push("${env.BUILD_NUMBER}")
            pushapp.push("latest")
            }
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app_sql.push("${env.BUILD_NUMBER}")
            app_sql.push("latest")
   sh "docker push lucasducau/wordpress_qqqq:${env.BUILD_NUMBER}"
    } */
            }
  }
  catch (Exception e)
  {
  echo "push failed"
  }

stage('Clean up'){
    app_golang.stop()


  }
}
